apiVersion: apps/v1
kind: Deployment
metadata:
  name: synonyms
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: synonyms
  template:
    metadata:
      labels:
        app.kubernetes.io/name: synonyms
    spec:
      containers:
        - name: synonyms
          image: harbor.nadileaf.com/ml-model/synonyms:cpu-1.0.0
